image: instrumentisto/rsync-ssh

variables:
  SSH_HOST: "139.162.197.19"
  SSH_USER: "ci"
  REMOTE_DIR: "/var/www/deeply.thenewhumanitarian.org/000_overrides/"

deploy to production:
  stage: deploy
  script:
  - mkdir "${HOME}/.ssh"
  - chmod 700 "${HOME}/.ssh"
  - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
  - chmod 600 "${HOME}/.ssh/id_rsa"
  - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
  - chmod 600 "${HOME}/.ssh/known_hosts"
  - echo "${SSH_CONFIG}" > "${HOME}/.ssh/config"
  - chmod 600 "${HOME}/.ssh/config"
  - rsync -hvvrzc --delete-after --exclude=.git -e "ssh -i ${HOME}/.ssh/id_rsa" ./ ${SSH_USER}@${SSH_HOST}:${REMOTE_DIR}
  environment:
    name: production
    url: https://deeply.thenewhumanitarian.org
  only:
  - master
